version: "3.8"

services:
  fastapi:
    build: ./backend
    ports:
      - "8000:8000"  # 로컬 개발 시 사용 (운영 시 reverse proxy로 대체)
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - EXTENSION_ID=${EXTENSION_ID}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    depends_on:
      mysql:
        condition: service_healthy
    env_file:
      - .env

  llm-worker-rec:
    build: ./llm-worker-rec
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PERPLEXITY_API_KEY=${PERPLEXITY_API_KEY}
    env_file:
      - .env

  llm-worker-youtube:
    build: ./llm-worker-youtube
    ports:
      - "50052:50052"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PERPLEXITY_API_KEY=${PERPLEXITY_API_KEY}
    env_file:
      - .env

  llm-worker-docs:
    build:
      context: ./llm-worker-docs
    container_name: llm-worker-docs
    ports:
      - "50053:50053"
    environment:
      - WATSONX_API_KEY=${WATSONX_API_KEY}
      - WATSONX_PROJECT_ID=${WATSONX_PROJECT_ID}
      - PERPLEXITY_API_KEY=${PERPLEXITY_API_KEY}
    env_file:
      - .env

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=penseur_db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  pdf-text-extractor:
    image: huridocs/pdf-document-layout-analysis:v0.0.23
    container_name: pdf-document-layout-analysis
    ports:
      - "5060:5060"
    command: [
      "gunicorn",
      "-k", "uvicorn.workers.UvicornWorker",
      "--chdir", "./src",
      "app:app",
      "--bind", "0.0.0.0:5060",
      "--timeout", "10000"
    ]

volumes:
  mysql_data: